export const STATIC_REAL_IMAGE_PREFIX = "static:";

export type RealPhotoAsset = {
  imageId: string;
  url: string;
  sourceRelativePath: string;
  target: "stud" | "environment" | "feeding";
  targetId: string;
  slot: "cover" | "gallery" | "room";
  order: number;
  originalFileName: string;
  outputFileName: string;
  sourceWidth: number;
  sourceHeight: number;
  outputWidth: number;
  outputHeight: number;
  sourceSizeBytes: number;
  outputSizeBytes: number;
  matchedName?: string;
  temporaryCover?: boolean;
  sectionId?: string;
  sectionTitle?: string;
  roomId?: string;
  roomTitle?: string;
};

export const REAL_PHOTO_ASSETS = [
  {
    imageId: "static:environment/kitten/room-1/1",
    url: "/real-photos/environment/kitten/room-1/1.jpg",
    sourceRelativePath: "猫舍环境/幼猫生活区√/小猫房1-00.jpg",
    target: "environment",
    targetId: "environment-zone-kitten",
    slot: "room",
    order: 1,
    originalFileName: "小猫房1-00.jpg",
    outputFileName: "1.jpg",
    sourceWidth: 3072,
    sourceHeight: 4096,
    outputWidth: 1500,
    outputHeight: 2000,
    sourceSizeBytes: 6952919,
    outputSizeBytes: 441088,
    sectionId: "environment-zone-kitten",
    sectionTitle: "幼猫生活区",
    roomId: "environment-room-kitten-1",
    roomTitle: "房间一",
  },
  {
    imageId: "static:environment/kitten/room-1/2",
    url: "/real-photos/environment/kitten/room-1/2.jpg",
    sourceRelativePath: "猫舍环境/幼猫生活区√/小猫房1-01.jpg",
    target: "environment",
    targetId: "environment-zone-kitten",
    slot: "room",
    order: 2,
    originalFileName: "小猫房1-01.jpg",
    outputFileName: "2.jpg",
    sourceWidth: 4096,
    sourceHeight: 3072,
    outputWidth: 2000,
    outputHeight: 1500,
    sourceSizeBytes: 5609757,
    outputSizeBytes: 340780,
    sectionId: "environment-zone-kitten",
    sectionTitle: "幼猫生活区",
    roomId: "environment-room-kitten-1",
    roomTitle: "房间一",
  },
  {
    imageId: "static:environment/kitten/room-1/3",
    url: "/real-photos/environment/kitten/room-1/3.jpg",
    sourceRelativePath: "猫舍环境/幼猫生活区√/小猫房1-02.jpg",
    target: "environment",
    targetId: "environment-zone-kitten",
    slot: "room",
    order: 3,
    originalFileName: "小猫房1-02.jpg",
    outputFileName: "3.jpg",
    sourceWidth: 3072,
    sourceHeight: 4096,
    outputWidth: 1500,
    outputHeight: 2000,
    sourceSizeBytes: 7302926,
    outputSizeBytes: 507639,
    sectionId: "environment-zone-kitten",
    sectionTitle: "幼猫生活区",
    roomId: "environment-room-kitten-1",
    roomTitle: "房间一",
  },
  {
    imageId: "static:environment/kitten/room-1/4",
    url: "/real-photos/environment/kitten/room-1/4.jpg",
    sourceRelativePath: "猫舍环境/幼猫生活区√/小猫房1-03.jpg",
    target: "environment",
    targetId: "environment-zone-kitten",
    slot: "room",
    order: 4,
    originalFileName: "小猫房1-03.jpg",
    outputFileName: "4.jpg",
    sourceWidth: 3072,
    sourceHeight: 4096,
    outputWidth: 1500,
    outputHeight: 2000,
    sourceSizeBytes: 6814179,
    outputSizeBytes: 494252,
    sectionId: "environment-zone-kitten",
    sectionTitle: "幼猫生活区",
    roomId: "environment-room-kitten-1",
    roomTitle: "房间一",
  },
  {
    imageId: "static:environment/kitten/room-2/1",
    url: "/real-photos/environment/kitten/room-2/1.jpg",
    sourceRelativePath: "猫舍环境/幼猫生活区√/小猫房2-00.jpg",
    target: "environment",
    targetId: "environment-zone-kitten",
    slot: "room",
    order: 1,
    originalFileName: "小猫房2-00.jpg",
    outputFileName: "1.jpg",
    sourceWidth: 3072,
    sourceHeight: 4096,
    outputWidth: 1500,
    outputHeight: 2000,
    sourceSizeBytes: 6560868,
    outputSizeBytes: 539879,
    sectionId: "environment-zone-kitten",
    sectionTitle: "幼猫生活区",
    roomId: "environment-room-kitten-2",
    roomTitle: "房间二",
  },
  {
    imageId: "static:environment/kitten/room-2/2",
    url: "/real-photos/environment/kitten/room-2/2.jpg",
    sourceRelativePath: "猫舍环境/幼猫生活区√/小猫房2-01.jpg",
    target: "environment",
    targetId: "environment-zone-kitten",
    slot: "room",
    order: 2,
    originalFileName: "小猫房2-01.jpg",
    outputFileName: "2.jpg",
    sourceWidth: 3072,
    sourceHeight: 4096,
    outputWidth: 1500,
    outputHeight: 2000,
    sourceSizeBytes: 4547147,
    outputSizeBytes: 425487,
    sectionId: "environment-zone-kitten",
    sectionTitle: "幼猫生活区",
    roomId: "environment-room-kitten-2",
    roomTitle: "房间二",
  },
  {
    imageId: "static:environment/kitten/room-2/3",
    url: "/real-photos/environment/kitten/room-2/3.jpg",
    sourceRelativePath: "猫舍环境/幼猫生活区√/小猫房2-02.jpg",
    target: "environment",
    targetId: "environment-zone-kitten",
    slot: "room",
    order: 3,
    originalFileName: "小猫房2-02.jpg",
    outputFileName: "3.jpg",
    sourceWidth: 3072,
    sourceHeight: 4096,
    outputWidth: 1500,
    outputHeight: 2000,
    sourceSizeBytes: 5012673,
    outputSizeBytes: 464720,
    sectionId: "environment-zone-kitten",
    sectionTitle: "幼猫生活区",
    roomId: "environment-room-kitten-2",
    roomTitle: "房间二",
  },
  {
    imageId: "static:environment/kitten/room-3/1",
    url: "/real-photos/environment/kitten/room-3/1.jpg",
    sourceRelativePath: "猫舍环境/幼猫生活区√/小猫房3-00.jpg",
    target: "environment",
    targetId: "environment-zone-kitten",
    slot: "room",
    order: 1,
    originalFileName: "小猫房3-00.jpg",
    outputFileName: "1.jpg",
    sourceWidth: 3072,
    sourceHeight: 4096,
    outputWidth: 1500,
    outputHeight: 2000,
    sourceSizeBytes: 7656579,
    outputSizeBytes: 541224,
    sectionId: "environment-zone-kitten",
    sectionTitle: "幼猫生活区",
    roomId: "environment-room-kitten-3",
    roomTitle: "房间三",
  },
  {
    imageId: "static:environment/kitten/room-3/2",
    url: "/real-photos/environment/kitten/room-3/2.jpg",
    sourceRelativePath: "猫舍环境/幼猫生活区√/小猫房3-01.jpg",
    target: "environment",
    targetId: "environment-zone-kitten",
    slot: "room",
    order: 2,
    originalFileName: "小猫房3-01.jpg",
    outputFileName: "2.jpg",
    sourceWidth: 4096,
    sourceHeight: 3072,
    outputWidth: 2000,
    outputHeight: 1500,
    sourceSizeBytes: 7700739,
    outputSizeBytes: 575321,
    sectionId: "environment-zone-kitten",
    sectionTitle: "幼猫生活区",
    roomId: "environment-room-kitten-3",
    roomTitle: "房间三",
  },
  {
    imageId: "static:environment/kitten/room-3/3",
    url: "/real-photos/environment/kitten/room-3/3.jpg",
    sourceRelativePath: "猫舍环境/幼猫生活区√/小猫房3-02.jpg",
    target: "environment",
    targetId: "environment-zone-kitten",
    slot: "room",
    order: 3,
    originalFileName: "小猫房3-02.jpg",
    outputFileName: "3.jpg",
    sourceWidth: 4096,
    sourceHeight: 3072,
    outputWidth: 2000,
    outputHeight: 1500,
    sourceSizeBytes: 7432647,
    outputSizeBytes: 509287,
    sectionId: "environment-zone-kitten",
    sectionTitle: "幼猫生活区",
    roomId: "environment-room-kitten-3",
    roomTitle: "房间三",
  },
  {
    imageId: "static:environment/kitten/room-common/1",
    url: "/real-photos/environment/kitten/room-common/1.jpg",
    sourceRelativePath: "猫舍环境/幼猫生活区√/小猫房大-00.jpg",
    target: "environment",
    targetId: "environment-zone-kitten",
    slot: "room",
    order: 1,
    originalFileName: "小猫房大-00.jpg",
    outputFileName: "1.jpg",
    sourceWidth: 3072,
    sourceHeight: 4096,
    outputWidth: 1500,
    outputHeight: 2000,
    sourceSizeBytes: 6224097,
    outputSizeBytes: 399921,
    sectionId: "environment-zone-kitten",
    sectionTitle: "幼猫生活区",
    roomId: "environment-room-kitten-common",
    roomTitle: "大活动房",
  },
  {
    imageId: "static:environment/kitten/room-common/2",
    url: "/real-photos/environment/kitten/room-common/2.jpg",
    sourceRelativePath: "猫舍环境/幼猫生活区√/小猫房大-01.jpg",
    target: "environment",
    targetId: "environment-zone-kitten",
    slot: "room",
    order: 2,
    originalFileName: "小猫房大-01.jpg",
    outputFileName: "2.jpg",
    sourceWidth: 4096,
    sourceHeight: 3072,
    outputWidth: 2000,
    outputHeight: 1500,
    sourceSizeBytes: 6711088,
    outputSizeBytes: 427153,
    sectionId: "environment-zone-kitten",
    sectionTitle: "幼猫生活区",
    roomId: "environment-room-kitten-common",
    roomTitle: "大活动房",
  },
  {
    imageId: "static:environment/kitten/room-common/3",
    url: "/real-photos/environment/kitten/room-common/3.jpg",
    sourceRelativePath: "猫舍环境/幼猫生活区√/小猫房大-02.jpg",
    target: "environment",
    targetId: "environment-zone-kitten",
    slot: "room",
    order: 3,
    originalFileName: "小猫房大-02.jpg",
    outputFileName: "3.jpg",
    sourceWidth: 3072,
    sourceHeight: 4096,
    outputWidth: 1500,
    outputHeight: 2000,
    sourceSizeBytes: 6464746,
    outputSizeBytes: 357733,
    sectionId: "environment-zone-kitten",
    sectionTitle: "幼猫生活区",
    roomId: "environment-room-kitten-common",
    roomTitle: "大活动房",
  },
  {
    imageId: "static:environment/kitten/room-common/4",
    url: "/real-photos/environment/kitten/room-common/4.jpg",
    sourceRelativePath: "猫舍环境/幼猫生活区√/小猫房大-03.jpg",
    target: "environment",
    targetId: "environment-zone-kitten",
    slot: "room",
    order: 4,
    originalFileName: "小猫房大-03.jpg",
    outputFileName: "4.jpg",
    sourceWidth: 4080,
    sourceHeight: 3060,
    outputWidth: 2000,
    outputHeight: 1500,
    sourceSizeBytes: 5166672,
    outputSizeBytes: 329048,
    sectionId: "environment-zone-kitten",
    sectionTitle: "幼猫生活区",
    roomId: "environment-room-kitten-common",
    roomTitle: "大活动房",
  },
  {
    imageId: "static:environment/kitten/room-common/5",
    url: "/real-photos/environment/kitten/room-common/5.jpg",
    sourceRelativePath: "猫舍环境/幼猫生活区√/小猫房大-04.jpg",
    target: "environment",
    targetId: "environment-zone-kitten",
    slot: "room",
    order: 5,
    originalFileName: "小猫房大-04.jpg",
    outputFileName: "5.jpg",
    sourceWidth: 3072,
    sourceHeight: 4096,
    outputWidth: 1500,
    outputHeight: 2000,
    sourceSizeBytes: 6313435,
    outputSizeBytes: 387128,
    sectionId: "environment-zone-kitten",
    sectionTitle: "幼猫生活区",
    roomId: "environment-room-kitten-common",
    roomTitle: "大活动房",
  },
  {
    imageId: "static:environment/queen/room-1/1",
    url: "/real-photos/environment/queen/room-1/1.jpg",
    sourceRelativePath: "猫舍环境/母猫生活区√/母猫房1-00.jpg",
    target: "environment",
    targetId: "environment-zone-queen",
    slot: "room",
    order: 1,
    originalFileName: "母猫房1-00.jpg",
    outputFileName: "1.jpg",
    sourceWidth: 3072,
    sourceHeight: 4096,
    outputWidth: 1500,
    outputHeight: 2000,
    sourceSizeBytes: 6526361,
    outputSizeBytes: 425602,
    sectionId: "environment-zone-queen",
    sectionTitle: "种母生活区",
    roomId: "environment-room-queen-1",
    roomTitle: "房间一",
  },
  {
    imageId: "static:environment/queen/room-1/2",
    url: "/real-photos/environment/queen/room-1/2.jpg",
    sourceRelativePath: "猫舍环境/母猫生活区√/母猫房1-01.jpg",
    target: "environment",
    targetId: "environment-zone-queen",
    slot: "room",
    order: 2,
    originalFileName: "母猫房1-01.jpg",
    outputFileName: "2.jpg",
    sourceWidth: 3072,
    sourceHeight: 4096,
    outputWidth: 1500,
    outputHeight: 2000,
    sourceSizeBytes: 4341089,
    outputSizeBytes: 266651,
    sectionId: "environment-zone-queen",
    sectionTitle: "种母生活区",
    roomId: "environment-room-queen-1",
    roomTitle: "房间一",
  },
  {
    imageId: "static:environment/queen/room-1/3",
    url: "/real-photos/environment/queen/room-1/3.jpg",
    sourceRelativePath: "猫舍环境/母猫生活区√/母猫房1-02.jpg",
    target: "environment",
    targetId: "environment-zone-queen",
    slot: "room",
    order: 3,
    originalFileName: "母猫房1-02.jpg",
    outputFileName: "3.jpg",
    sourceWidth: 4096,
    sourceHeight: 3072,
    outputWidth: 2000,
    outputHeight: 1500,
    sourceSizeBytes: 5771300,
    outputSizeBytes: 415557,
    sectionId: "environment-zone-queen",
    sectionTitle: "种母生活区",
    roomId: "environment-room-queen-1",
    roomTitle: "房间一",
  },
  {
    imageId: "static:environment/queen/room-1/4",
    url: "/real-photos/environment/queen/room-1/4.jpg",
    sourceRelativePath: "猫舍环境/母猫生活区√/母猫房1-03.jpg",
    target: "environment",
    targetId: "environment-zone-queen",
    slot: "room",
    order: 4,
    originalFileName: "母猫房1-03.jpg",
    outputFileName: "4.jpg",
    sourceWidth: 4096,
    sourceHeight: 3072,
    outputWidth: 2000,
    outputHeight: 1500,
    sourceSizeBytes: 5547545,
    outputSizeBytes: 429839,
    sectionId: "environment-zone-queen",
    sectionTitle: "种母生活区",
    roomId: "environment-room-queen-1",
    roomTitle: "房间一",
  },
  {
    imageId: "static:environment/queen/room-1/5",
    url: "/real-photos/environment/queen/room-1/5.jpg",
    sourceRelativePath: "猫舍环境/母猫生活区√/母猫房1-04.jpg",
    target: "environment",
    targetId: "environment-zone-queen",
    slot: "room",
    order: 5,
    originalFileName: "母猫房1-04.jpg",
    outputFileName: "5.jpg",
    sourceWidth: 3072,
    sourceHeight: 4096,
    outputWidth: 1500,
    outputHeight: 2000,
    sourceSizeBytes: 5442988,
    outputSizeBytes: 405893,
    sectionId: "environment-zone-queen",
    sectionTitle: "种母生活区",
    roomId: "environment-room-queen-1",
    roomTitle: "房间一",
  },
  {
    imageId: "static:environment/queen/room-2/1",
    url: "/real-photos/environment/queen/room-2/1.jpg",
    sourceRelativePath: "猫舍环境/母猫生活区√/母猫房2-00.jpg",
    target: "environment",
    targetId: "environment-zone-queen",
    slot: "room",
    order: 1,
    originalFileName: "母猫房2-00.jpg",
    outputFileName: "1.jpg",
    sourceWidth: 3072,
    sourceHeight: 4096,
    outputWidth: 1500,
    outputHeight: 2000,
    sourceSizeBytes: 7097871,
    outputSizeBytes: 502399,
    sectionId: "environment-zone-queen",
    sectionTitle: "种母生活区",
    roomId: "environment-room-queen-2",
    roomTitle: "房间二",
  },
  {
    imageId: "static:environment/queen/room-2/2",
    url: "/real-photos/environment/queen/room-2/2.jpg",
    sourceRelativePath: "猫舍环境/母猫生活区√/母猫房2-01.jpg",
    target: "environment",
    targetId: "environment-zone-queen",
    slot: "room",
    order: 2,
    originalFileName: "母猫房2-01.jpg",
    outputFileName: "2.jpg",
    sourceWidth: 4096,
    sourceHeight: 3072,
    outputWidth: 2000,
    outputHeight: 1500,
    sourceSizeBytes: 8553963,
    outputSizeBytes: 603679,
    sectionId: "environment-zone-queen",
    sectionTitle: "种母生活区",
    roomId: "environment-room-queen-2",
    roomTitle: "房间二",
  },
  {
    imageId: "static:environment/queen/room-2/3",
    url: "/real-photos/environment/queen/room-2/3.jpg",
    sourceRelativePath: "猫舍环境/母猫生活区√/母猫房2-02.jpg",
    target: "environment",
    targetId: "environment-zone-queen",
    slot: "room",
    order: 3,
    originalFileName: "母猫房2-02.jpg",
    outputFileName: "3.jpg",
    sourceWidth: 4096,
    sourceHeight: 3072,
    outputWidth: 2000,
    outputHeight: 1500,
    sourceSizeBytes: 4299535,
    outputSizeBytes: 355277,
    sectionId: "environment-zone-queen",
    sectionTitle: "种母生活区",
    roomId: "environment-room-queen-2",
    roomTitle: "房间二",
  },
  {
    imageId: "static:environment/queen/room-3/1",
    url: "/real-photos/environment/queen/room-3/1.jpg",
    sourceRelativePath: "猫舍环境/母猫生活区√/母猫房3-00.jpg",
    target: "environment",
    targetId: "environment-zone-queen",
    slot: "room",
    order: 1,
    originalFileName: "母猫房3-00.jpg",
    outputFileName: "1.jpg",
    sourceWidth: 3072,
    sourceHeight: 4096,
    outputWidth: 1500,
    outputHeight: 2000,
    sourceSizeBytes: 5484237,
    outputSizeBytes: 378852,
    sectionId: "environment-zone-queen",
    sectionTitle: "种母生活区",
    roomId: "environment-room-queen-3",
    roomTitle: "房间三",
  },
  {
    imageId: "static:environment/queen/room-3/2",
    url: "/real-photos/environment/queen/room-3/2.jpg",
    sourceRelativePath: "猫舍环境/母猫生活区√/母猫房3-01.jpg",
    target: "environment",
    targetId: "environment-zone-queen",
    slot: "room",
    order: 2,
    originalFileName: "母猫房3-01.jpg",
    outputFileName: "2.jpg",
    sourceWidth: 4096,
    sourceHeight: 3072,
    outputWidth: 2000,
    outputHeight: 1500,
    sourceSizeBytes: 3775711,
    outputSizeBytes: 318521,
    sectionId: "environment-zone-queen",
    sectionTitle: "种母生活区",
    roomId: "environment-room-queen-3",
    roomTitle: "房间三",
  },
  {
    imageId: "static:environment/queen/room-3/3",
    url: "/real-photos/environment/queen/room-3/3.jpg",
    sourceRelativePath: "猫舍环境/母猫生活区√/母猫房3-02.jpg",
    target: "environment",
    targetId: "environment-zone-queen",
    slot: "room",
    order: 3,
    originalFileName: "母猫房3-02.jpg",
    outputFileName: "3.jpg",
    sourceWidth: 3072,
    sourceHeight: 4096,
    outputWidth: 1500,
    outputHeight: 2000,
    sourceSizeBytes: 4121054,
    outputSizeBytes: 287304,
    sectionId: "environment-zone-queen",
    sectionTitle: "种母生活区",
    roomId: "environment-room-queen-3",
    roomTitle: "房间三",
  },
  {
    imageId: "static:environment/queen/room-4/1",
    url: "/real-photos/environment/queen/room-4/1.jpg",
    sourceRelativePath: "猫舍环境/母猫生活区√/母猫房4-00.jpg",
    target: "environment",
    targetId: "environment-zone-queen",
    slot: "room",
    order: 1,
    originalFileName: "母猫房4-00.jpg",
    outputFileName: "1.jpg",
    sourceWidth: 3072,
    sourceHeight: 4096,
    outputWidth: 1500,
    outputHeight: 2000,
    sourceSizeBytes: 5051317,
    outputSizeBytes: 364087,
    sectionId: "environment-zone-queen",
    sectionTitle: "种母生活区",
    roomId: "environment-room-queen-4",
    roomTitle: "房间四",
  },
  {
    imageId: "static:environment/queen/room-4/2",
    url: "/real-photos/environment/queen/room-4/2.jpg",
    sourceRelativePath: "猫舍环境/母猫生活区√/母猫房4-01.jpg",
    target: "environment",
    targetId: "environment-zone-queen",
    slot: "room",
    order: 2,
    originalFileName: "母猫房4-01.jpg",
    outputFileName: "2.jpg",
    sourceWidth: 4096,
    sourceHeight: 3072,
    outputWidth: 2000,
    outputHeight: 1500,
    sourceSizeBytes: 4141050,
    outputSizeBytes: 389911,
    sectionId: "environment-zone-queen",
    sectionTitle: "种母生活区",
    roomId: "environment-room-queen-4",
    roomTitle: "房间四",
  },
  {
    imageId: "static:environment/queen/room-4/3",
    url: "/real-photos/environment/queen/room-4/3.jpg",
    sourceRelativePath: "猫舍环境/母猫生活区√/母猫房4-03.jpg",
    target: "environment",
    targetId: "environment-zone-queen",
    slot: "room",
    order: 3,
    originalFileName: "母猫房4-03.jpg",
    outputFileName: "3.jpg",
    sourceWidth: 3072,
    sourceHeight: 4096,
    outputWidth: 1500,
    outputHeight: 2000,
    sourceSizeBytes: 3766898,
    outputSizeBytes: 286142,
    sectionId: "environment-zone-queen",
    sectionTitle: "种母生活区",
    roomId: "environment-room-queen-4",
    roomTitle: "房间四",
  },
  {
    imageId: "static:studs/chonglou/cover",
    url: "/real-photos/studs/chonglou/cover.jpg",
    sourceRelativePath: "我们的猫丨种猫/公猫/种猫-重楼-00.jpg",
    target: "stud",
    targetId: "chonglou",
    slot: "cover",
    order: 1,
    originalFileName: "种猫-重楼-00.jpg",
    outputFileName: "cover.jpg",
    sourceWidth: 1260,
    sourceHeight: 2800,
    outputWidth: 900,
    outputHeight: 2000,
    sourceSizeBytes: 733592,
    outputSizeBytes: 139830,
    matchedName: "重楼",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/chonglou/gallery-1",
    url: "/real-photos/studs/chonglou/gallery-1.jpg",
    sourceRelativePath: "我们的猫丨种猫/公猫/种猫-重楼-01.jpg",
    target: "stud",
    targetId: "chonglou",
    slot: "gallery",
    order: 2,
    originalFileName: "种猫-重楼-01.jpg",
    outputFileName: "gallery-1.jpg",
    sourceWidth: 1260,
    sourceHeight: 2800,
    outputWidth: 900,
    outputHeight: 2000,
    sourceSizeBytes: 758509,
    outputSizeBytes: 142139,
    matchedName: "重楼",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/chonglou/gallery-2",
    url: "/real-photos/studs/chonglou/gallery-2.jpg",
    sourceRelativePath: "我们的猫丨种猫/公猫/种猫-重楼-02.jpg",
    target: "stud",
    targetId: "chonglou",
    slot: "gallery",
    order: 3,
    originalFileName: "种猫-重楼-02.jpg",
    outputFileName: "gallery-2.jpg",
    sourceWidth: 1260,
    sourceHeight: 2800,
    outputWidth: 900,
    outputHeight: 2000,
    sourceSizeBytes: 697050,
    outputSizeBytes: 131065,
    matchedName: "重楼",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/guihuagao/cover",
    url: "/real-photos/studs/guihuagao/cover.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-桂花糕-00.jpg",
    target: "stud",
    targetId: "guihuagao",
    slot: "cover",
    order: 1,
    originalFileName: "种猫-桂花糕-00.jpg",
    outputFileName: "cover.jpg",
    sourceWidth: 1080,
    sourceHeight: 1616,
    outputWidth: 1080,
    outputHeight: 1616,
    sourceSizeBytes: 1305219,
    outputSizeBytes: 400378,
    matchedName: "桂花糕",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/guihuagao/gallery-1",
    url: "/real-photos/studs/guihuagao/gallery-1.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-桂花糕-01.jpg",
    target: "stud",
    targetId: "guihuagao",
    slot: "gallery",
    order: 2,
    originalFileName: "种猫-桂花糕-01.jpg",
    outputFileName: "gallery-1.jpg",
    sourceWidth: 1080,
    sourceHeight: 1616,
    outputWidth: 1080,
    outputHeight: 1616,
    sourceSizeBytes: 1311817,
    outputSizeBytes: 403958,
    matchedName: "桂花糕",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/guihuagao/gallery-2",
    url: "/real-photos/studs/guihuagao/gallery-2.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-桂花糕-02.jpg",
    target: "stud",
    targetId: "guihuagao",
    slot: "gallery",
    order: 3,
    originalFileName: "种猫-桂花糕-02.jpg",
    outputFileName: "gallery-2.jpg",
    sourceWidth: 1080,
    sourceHeight: 1616,
    outputWidth: 1080,
    outputHeight: 1616,
    sourceSizeBytes: 1288993,
    outputSizeBytes: 370193,
    matchedName: "桂花糕",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/huqing/cover",
    url: "/real-photos/studs/huqing/cover.jpg",
    sourceRelativePath: "我们的猫丨种猫/公猫/种猫-虎晴-00.jpg",
    target: "stud",
    targetId: "huqing",
    slot: "cover",
    order: 1,
    originalFileName: "种猫-虎晴-00.jpg",
    outputFileName: "cover.jpg",
    sourceWidth: 2732,
    sourceHeight: 4096,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 7069502,
    outputSizeBytes: 346127,
    matchedName: "虎晴",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/huqing/gallery-1",
    url: "/real-photos/studs/huqing/gallery-1.jpg",
    sourceRelativePath: "我们的猫丨种猫/公猫/种猫-虎晴-01.jpg",
    target: "stud",
    targetId: "huqing",
    slot: "gallery",
    order: 2,
    originalFileName: "种猫-虎晴-01.jpg",
    outputFileName: "gallery-1.jpg",
    sourceWidth: 2732,
    sourceHeight: 4096,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 7518799,
    outputSizeBytes: 450831,
    matchedName: "虎晴",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/huqing/gallery-2",
    url: "/real-photos/studs/huqing/gallery-2.jpg",
    sourceRelativePath: "我们的猫丨种猫/公猫/种猫-虎晴-02.jpg",
    target: "stud",
    targetId: "huqing",
    slot: "gallery",
    order: 3,
    originalFileName: "种猫-虎晴-02.jpg",
    outputFileName: "gallery-2.jpg",
    sourceWidth: 3346,
    sourceHeight: 5016,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 7427184,
    outputSizeBytes: 334720,
    matchedName: "虎晴",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/manao/cover",
    url: "/real-photos/studs/manao/cover.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-玛瑙-00.jpg",
    target: "stud",
    targetId: "manao",
    slot: "cover",
    order: 1,
    originalFileName: "种猫-玛瑙-00.jpg",
    outputFileName: "cover.jpg",
    sourceWidth: 3346,
    sourceHeight: 5016,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 8953841,
    outputSizeBytes: 326333,
    matchedName: "玛瑙",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/manao/gallery-1",
    url: "/real-photos/studs/manao/gallery-1.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-玛瑙-01.jpg",
    target: "stud",
    targetId: "manao",
    slot: "gallery",
    order: 2,
    originalFileName: "种猫-玛瑙-01.jpg",
    outputFileName: "gallery-1.jpg",
    sourceWidth: 3346,
    sourceHeight: 5016,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 9475334,
    outputSizeBytes: 425102,
    matchedName: "玛瑙",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/manao/gallery-2",
    url: "/real-photos/studs/manao/gallery-2.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-玛瑙-02.jpg",
    target: "stud",
    targetId: "manao",
    slot: "gallery",
    order: 3,
    originalFileName: "种猫-玛瑙-02.jpg",
    outputFileName: "gallery-2.jpg",
    sourceWidth: 4096,
    sourceHeight: 2732,
    outputWidth: 2000,
    outputHeight: 1334,
    sourceSizeBytes: 7453957,
    outputSizeBytes: 419431,
    matchedName: "玛瑙",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/shulongyin/cover",
    url: "/real-photos/studs/shulongyin/cover.jpg",
    sourceRelativePath: "我们的猫丨种猫/公猫/种猫-水龙吟-00.jpg",
    target: "stud",
    targetId: "shulongyin",
    slot: "cover",
    order: 1,
    originalFileName: "种猫-水龙吟-00.jpg",
    outputFileName: "cover.jpg",
    sourceWidth: 5304,
    sourceHeight: 7952,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 17185139,
    outputSizeBytes: 273569,
    matchedName: "水龙吟",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/shulongyin/gallery-1",
    url: "/real-photos/studs/shulongyin/gallery-1.jpg",
    sourceRelativePath: "我们的猫丨种猫/公猫/种猫-水龙吟-01.jpg",
    target: "stud",
    targetId: "shulongyin",
    slot: "gallery",
    order: 2,
    originalFileName: "种猫-水龙吟-01.jpg",
    outputFileName: "gallery-1.jpg",
    sourceWidth: 5304,
    sourceHeight: 7952,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 16973702,
    outputSizeBytes: 259804,
    matchedName: "水龙吟",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/shulongyin/gallery-2",
    url: "/real-photos/studs/shulongyin/gallery-2.jpg",
    sourceRelativePath: "我们的猫丨种猫/公猫/种猫-水龙吟-02.jpg",
    target: "stud",
    targetId: "shulongyin",
    slot: "gallery",
    order: 3,
    originalFileName: "种猫-水龙吟-02.jpg",
    outputFileName: "gallery-2.jpg",
    sourceWidth: 5304,
    sourceHeight: 7952,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 17095428,
    outputSizeBytes: 239024,
    matchedName: "水龙吟",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/tianhe/cover",
    url: "/real-photos/studs/tianhe/cover.jpg",
    sourceRelativePath: "我们的猫丨种猫/公猫/种猫-天河-00.jpg",
    target: "stud",
    targetId: "tianhe",
    slot: "cover",
    order: 1,
    originalFileName: "种猫-天河-00.jpg",
    outputFileName: "cover.jpg",
    sourceWidth: 3346,
    sourceHeight: 5016,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 8668850,
    outputSizeBytes: 291837,
    matchedName: "天河",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/tianhe/gallery-1",
    url: "/real-photos/studs/tianhe/gallery-1.jpg",
    sourceRelativePath: "我们的猫丨种猫/公猫/种猫-天河-01.jpg",
    target: "stud",
    targetId: "tianhe",
    slot: "gallery",
    order: 2,
    originalFileName: "种猫-天河-01.jpg",
    outputFileName: "gallery-1.jpg",
    sourceWidth: 3346,
    sourceHeight: 5016,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 9974125,
    outputSizeBytes: 405397,
    matchedName: "天河",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/tianhe/gallery-2",
    url: "/real-photos/studs/tianhe/gallery-2.jpg",
    sourceRelativePath: "我们的猫丨种猫/公猫/种猫-天河-02.jpg",
    target: "stud",
    targetId: "tianhe",
    slot: "gallery",
    order: 3,
    originalFileName: "种猫-天河-02.jpg",
    outputFileName: "gallery-2.jpg",
    sourceWidth: 3346,
    sourceHeight: 5016,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 8124506,
    outputSizeBytes: 250661,
    matchedName: "天河",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/xiaobianmu/cover",
    url: "/real-photos/studs/xiaobianmu/cover.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-小边牧-00.jpg",
    target: "stud",
    targetId: "xiaobianmu",
    slot: "cover",
    order: 1,
    originalFileName: "种猫-小边牧-00.jpg",
    outputFileName: "cover.jpg",
    sourceWidth: 3346,
    sourceHeight: 5016,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 9710518,
    outputSizeBytes: 477821,
    matchedName: "小边牧",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/xiaobianmu/gallery-1",
    url: "/real-photos/studs/xiaobianmu/gallery-1.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-小边牧-01.jpg",
    target: "stud",
    targetId: "xiaobianmu",
    slot: "gallery",
    order: 2,
    originalFileName: "种猫-小边牧-01.jpg",
    outputFileName: "gallery-1.jpg",
    sourceWidth: 3346,
    sourceHeight: 5016,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 9412084,
    outputSizeBytes: 405955,
    matchedName: "小边牧",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/xiaobianmu/gallery-2",
    url: "/real-photos/studs/xiaobianmu/gallery-2.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-小边牧-02.jpg",
    target: "stud",
    targetId: "xiaobianmu",
    slot: "gallery",
    order: 3,
    originalFileName: "种猫-小边牧-02.jpg",
    outputFileName: "gallery-2.jpg",
    sourceWidth: 3346,
    sourceHeight: 5016,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 9076145,
    outputSizeBytes: 377893,
    matchedName: "小边牧",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/xiaotao/cover",
    url: "/real-photos/studs/xiaotao/cover.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-小桃-00.jpg",
    target: "stud",
    targetId: "xiaotao",
    slot: "cover",
    order: 1,
    originalFileName: "种猫-小桃-00.jpg",
    outputFileName: "cover.jpg",
    sourceWidth: 2732,
    sourceHeight: 4096,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 7645495,
    outputSizeBytes: 485521,
    matchedName: "小桃",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/xiaotao/gallery-1",
    url: "/real-photos/studs/xiaotao/gallery-1.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-小桃-01.jpg",
    target: "stud",
    targetId: "xiaotao",
    slot: "gallery",
    order: 2,
    originalFileName: "种猫-小桃-01.jpg",
    outputFileName: "gallery-1.jpg",
    sourceWidth: 3346,
    sourceHeight: 5016,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 8601141,
    outputSizeBytes: 330286,
    matchedName: "小桃",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/xiaotao/gallery-2",
    url: "/real-photos/studs/xiaotao/gallery-2.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-小桃-02.jpg",
    target: "stud",
    targetId: "xiaotao",
    slot: "gallery",
    order: 3,
    originalFileName: "种猫-小桃-02.jpg",
    outputFileName: "gallery-2.jpg",
    sourceWidth: 3346,
    sourceHeight: 5016,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 8714713,
    outputSizeBytes: 385114,
    matchedName: "小桃",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/luoyiyi/cover",
    url: "/real-photos/studs/luoyiyi/cover.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-依依-00.jpg",
    target: "stud",
    targetId: "luoyiyi",
    slot: "cover",
    order: 1,
    originalFileName: "种猫-依依-00.jpg",
    outputFileName: "cover.jpg",
    sourceWidth: 2732,
    sourceHeight: 4096,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 7987784,
    outputSizeBytes: 310290,
    matchedName: "依依",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/luoyiyi/gallery-1",
    url: "/real-photos/studs/luoyiyi/gallery-1.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-依依-01.jpg",
    target: "stud",
    targetId: "luoyiyi",
    slot: "gallery",
    order: 2,
    originalFileName: "种猫-依依-01.jpg",
    outputFileName: "gallery-1.jpg",
    sourceWidth: 3346,
    sourceHeight: 5016,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 8679754,
    outputSizeBytes: 219333,
    matchedName: "依依",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/luoyiyi/gallery-2",
    url: "/real-photos/studs/luoyiyi/gallery-2.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-依依-02.jpg",
    target: "stud",
    targetId: "luoyiyi",
    slot: "gallery",
    order: 3,
    originalFileName: "种猫-依依-02.jpg",
    outputFileName: "gallery-2.jpg",
    sourceWidth: 3346,
    sourceHeight: 5016,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 8531927,
    outputSizeBytes: 207939,
    matchedName: "依依",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/xiaoxiaxian/cover",
    url: "/real-photos/studs/xiaoxiaxian/cover.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-小虾-00.jpg",
    target: "stud",
    targetId: "xiaoxiaxian",
    slot: "cover",
    order: 1,
    originalFileName: "种猫-小虾-00.jpg",
    outputFileName: "cover.jpg",
    sourceWidth: 3346,
    sourceHeight: 5016,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 8569845,
    outputSizeBytes: 176595,
    matchedName: "小虾",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/xiaoxiaxian/gallery-1",
    url: "/real-photos/studs/xiaoxiaxian/gallery-1.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-小虾-01.jpg",
    target: "stud",
    targetId: "xiaoxiaxian",
    slot: "gallery",
    order: 2,
    originalFileName: "种猫-小虾-01.jpg",
    outputFileName: "gallery-1.jpg",
    sourceWidth: 3346,
    sourceHeight: 5016,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 7923904,
    outputSizeBytes: 136334,
    matchedName: "小虾",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/xiaoxiaxian/gallery-2",
    url: "/real-photos/studs/xiaoxiaxian/gallery-2.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-小虾-02.jpg",
    target: "stud",
    targetId: "xiaoxiaxian",
    slot: "gallery",
    order: 3,
    originalFileName: "种猫-小虾-02.jpg",
    outputFileName: "gallery-2.jpg",
    sourceWidth: 3346,
    sourceHeight: 5016,
    outputWidth: 1334,
    outputHeight: 2000,
    sourceSizeBytes: 9207158,
    outputSizeBytes: 208889,
    matchedName: "小虾",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/yunmu/cover",
    url: "/real-photos/studs/yunmu/cover.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-云母-00.jpg",
    target: "stud",
    targetId: "yunmu",
    slot: "cover",
    order: 1,
    originalFileName: "种猫-云母-00.jpg",
    outputFileName: "cover.jpg",
    sourceWidth: 1080,
    sourceHeight: 1616,
    outputWidth: 1080,
    outputHeight: 1616,
    sourceSizeBytes: 671115,
    outputSizeBytes: 165749,
    matchedName: "云母",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/yunmu/gallery-1",
    url: "/real-photos/studs/yunmu/gallery-1.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-云母-01.jpg",
    target: "stud",
    targetId: "yunmu",
    slot: "gallery",
    order: 2,
    originalFileName: "种猫-云母-01.jpg",
    outputFileName: "gallery-1.jpg",
    sourceWidth: 1080,
    sourceHeight: 1616,
    outputWidth: 1080,
    outputHeight: 1616,
    sourceSizeBytes: 139453,
    outputSizeBytes: 125578,
    matchedName: "云母",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/yunmu/gallery-2",
    url: "/real-photos/studs/yunmu/gallery-2.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-云母-02.jpg",
    target: "stud",
    targetId: "yunmu",
    slot: "gallery",
    order: 3,
    originalFileName: "种猫-云母-02.jpg",
    outputFileName: "gallery-2.jpg",
    sourceWidth: 1279,
    sourceHeight: 1706,
    outputWidth: 1279,
    outputHeight: 1706,
    sourceSizeBytes: 253424,
    outputSizeBytes: 261116,
    matchedName: "云母",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/yunmu/gallery-3",
    url: "/real-photos/studs/yunmu/gallery-3.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-云母-03.jpg",
    target: "stud",
    targetId: "yunmu",
    slot: "gallery",
    order: 4,
    originalFileName: "种猫-云母-03.jpg",
    outputFileName: "gallery-3.jpg",
    sourceWidth: 778,
    sourceHeight: 837,
    outputWidth: 778,
    outputHeight: 837,
    sourceSizeBytes: 174889,
    outputSizeBytes: 44943,
    matchedName: "云母",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/zhaoyue/cover",
    url: "/real-photos/studs/zhaoyue/cover.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-昭月-01.jpg",
    target: "stud",
    targetId: "zhaoyue",
    slot: "cover",
    order: 1,
    originalFileName: "种猫-昭月-01.jpg",
    outputFileName: "cover.jpg",
    sourceWidth: 1080,
    sourceHeight: 1616,
    outputWidth: 1080,
    outputHeight: 1616,
    sourceSizeBytes: 96485,
    outputSizeBytes: 110724,
    matchedName: "昭月",
    temporaryCover: true,
  },
  {
    imageId: "static:studs/zhaoyue/gallery-1",
    url: "/real-photos/studs/zhaoyue/gallery-1.jpg",
    sourceRelativePath: "我们的猫丨种猫/母猫/种猫-昭月-02.jpg",
    target: "stud",
    targetId: "zhaoyue",
    slot: "gallery",
    order: 2,
    originalFileName: "种猫-昭月-02.jpg",
    outputFileName: "gallery-1.jpg",
    sourceWidth: 1080,
    sourceHeight: 1616,
    outputWidth: 1080,
    outputHeight: 1616,
    sourceSizeBytes: 102192,
    outputSizeBytes: 117731,
    matchedName: "昭月",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/zhaoyue/gallery-2",
    url: "/real-photos/studs/zhaoyue/gallery-2.jpg",
    sourceRelativePath: "supplement/studs/zhaoyue-02.jpg",
    target: "stud",
    targetId: "zhaoyue",
    slot: "gallery",
    order: 3,
    originalFileName: "zhaoyue-02.jpg",
    outputFileName: "gallery-2.jpg",
    sourceWidth: 1080,
    sourceHeight: 1616,
    outputWidth: 1080,
    outputHeight: 1616,
    sourceSizeBytes: 102192,
    outputSizeBytes: 102192,
    matchedName: "zhaoyue",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/hupo/cover",
    url: "/real-photos/studs/hupo/cover.jpg",
    sourceRelativePath: "supplement/studs/hupo-00.jpg",
    target: "stud",
    targetId: "hupo",
    slot: "cover",
    order: 1,
    originalFileName: "hupo-00.jpg",
    outputFileName: "cover.jpg",
    sourceWidth: 1439,
    sourceHeight: 1080,
    outputWidth: 1439,
    outputHeight: 1080,
    sourceSizeBytes: 145809,
    outputSizeBytes: 145809,
    matchedName: "hupo",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/hupo/gallery-1",
    url: "/real-photos/studs/hupo/gallery-1.jpg",
    sourceRelativePath: "supplement/studs/hupo-01.jpg",
    target: "stud",
    targetId: "hupo",
    slot: "gallery",
    order: 2,
    originalFileName: "hupo-01.jpg",
    outputFileName: "gallery-1.jpg",
    sourceWidth: 1212,
    sourceHeight: 810,
    outputWidth: 1212,
    outputHeight: 810,
    sourceSizeBytes: 85116,
    outputSizeBytes: 85116,
    matchedName: "hupo",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/hupo/gallery-2",
    url: "/real-photos/studs/hupo/gallery-2.jpg",
    sourceRelativePath: "supplement/studs/hupo-02.jpg",
    target: "stud",
    targetId: "hupo",
    slot: "gallery",
    order: 3,
    originalFileName: "hupo-02.jpg",
    outputFileName: "gallery-2.jpg",
    sourceWidth: 1080,
    sourceHeight: 1440,
    outputWidth: 1080,
    outputHeight: 1440,
    sourceSizeBytes: 246854,
    outputSizeBytes: 246854,
    matchedName: "hupo",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/niaotuan/cover",
    url: "/real-photos/studs/niaotuan/cover.jpg",
    sourceRelativePath: "supplement/studs/niaotuan-00.jpg",
    target: "stud",
    targetId: "niaotuan",
    slot: "cover",
    order: 1,
    originalFileName: "niaotuan-00.jpg",
    outputFileName: "cover.jpg",
    sourceWidth: 810,
    sourceHeight: 1212,
    outputWidth: 810,
    outputHeight: 1212,
    sourceSizeBytes: 80880,
    outputSizeBytes: 80880,
    matchedName: "niaotuan",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/niaotuan/gallery-1",
    url: "/real-photos/studs/niaotuan/gallery-1.jpg",
    sourceRelativePath: "supplement/studs/niaotuan-01.jpg",
    target: "stud",
    targetId: "niaotuan",
    slot: "gallery",
    order: 2,
    originalFileName: "niaotuan-01.jpg",
    outputFileName: "gallery-1.jpg",
    sourceWidth: 1616,
    sourceHeight: 1080,
    outputWidth: 1616,
    outputHeight: 1080,
    sourceSizeBytes: 111035,
    outputSizeBytes: 111035,
    matchedName: "niaotuan",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/niaotuan/gallery-2",
    url: "/real-photos/studs/niaotuan/gallery-2.jpg",
    sourceRelativePath: "supplement/studs/niaotuan-02.jpg",
    target: "stud",
    targetId: "niaotuan",
    slot: "gallery",
    order: 3,
    originalFileName: "niaotuan-02.jpg",
    outputFileName: "gallery-2.jpg",
    sourceWidth: 810,
    sourceHeight: 1212,
    outputWidth: 810,
    outputHeight: 1212,
    sourceSizeBytes: 75557,
    outputSizeBytes: 75557,
    matchedName: "niaotuan",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/xiongmao/cover",
    url: "/real-photos/studs/xiongmao/cover.jpg",
    sourceRelativePath: "supplement/studs/xiongmao-00.jpg",
    target: "stud",
    targetId: "xiongmao",
    slot: "cover",
    order: 1,
    originalFileName: "xiongmao-00.jpg",
    outputFileName: "cover.jpg",
    sourceWidth: 1080,
    sourceHeight: 1616,
    outputWidth: 1080,
    outputHeight: 1616,
    sourceSizeBytes: 144451,
    outputSizeBytes: 144451,
    matchedName: "xiongmao",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/xiongmao/gallery-1",
    url: "/real-photos/studs/xiongmao/gallery-1.jpg",
    sourceRelativePath: "supplement/studs/xiongmao-01.jpg",
    target: "stud",
    targetId: "xiongmao",
    slot: "gallery",
    order: 2,
    originalFileName: "xiongmao-01.jpg",
    outputFileName: "gallery-1.jpg",
    sourceWidth: 2732,
    sourceHeight: 4096,
    outputWidth: 2732,
    outputHeight: 4096,
    sourceSizeBytes: 1362828,
    outputSizeBytes: 1362828,
    matchedName: "xiongmao",
    temporaryCover: false,
  },
  {
    imageId: "static:studs/xiongmao/gallery-2",
    url: "/real-photos/studs/xiongmao/gallery-2.jpg",
    sourceRelativePath: "supplement/studs/xiongmao-02.jpg",
    target: "stud",
    targetId: "xiongmao",
    slot: "gallery",
    order: 3,
    originalFileName: "xiongmao-02.jpg",
    outputFileName: "gallery-2.jpg",
    sourceWidth: 3346,
    sourceHeight: 5016,
    outputWidth: 3346,
    outputHeight: 5016,
    sourceSizeBytes: 2248513,
    outputSizeBytes: 2248513,
    matchedName: "xiongmao",
    temporaryCover: false,
  },
  {
    imageId: "static:environment/nursery/pregnancy/1",
    url: "/real-photos/environment/nursery/pregnancy/1.jpg",
    sourceRelativePath: "supplement/environment/nursery-1-00.jpg",
    target: "environment",
    targetId: "environment-zone-nursery",
    slot: "room",
    order: 1,
    originalFileName: "nursery-1-00.jpg",
    outputFileName: "1.jpg",
    sourceWidth: 1706,
    sourceHeight: 1279,
    outputWidth: 1706,
    outputHeight: 1279,
    sourceSizeBytes: 265104,
    outputSizeBytes: 265104,
    sectionId: "environment-zone-nursery",
    roomId: "environment-room-nursery-pregnancy",
  },
  {
    imageId: "static:environment/nursery/pregnancy/2",
    url: "/real-photos/environment/nursery/pregnancy/2.jpg",
    sourceRelativePath: "supplement/environment/nursery-2-00.jpg",
    target: "environment",
    targetId: "environment-zone-nursery",
    slot: "room",
    order: 2,
    originalFileName: "nursery-2-00.jpg",
    outputFileName: "2.jpg",
    sourceWidth: 1706,
    sourceHeight: 1279,
    outputWidth: 1706,
    outputHeight: 1279,
    sourceSizeBytes: 321999,
    outputSizeBytes: 321999,
    sectionId: "environment-zone-nursery",
    roomId: "environment-room-nursery-pregnancy",
  },
  {
    imageId: "static:environment/nursery/newborn/1",
    url: "/real-photos/environment/nursery/newborn/1.jpg",
    sourceRelativePath: "supplement/environment/nursery-3-00.jpg",
    target: "environment",
    targetId: "environment-zone-nursery",
    slot: "room",
    order: 1,
    originalFileName: "nursery-3-00.jpg",
    outputFileName: "1.jpg",
    sourceWidth: 1706,
    sourceHeight: 1279,
    outputWidth: 1706,
    outputHeight: 1279,
    sourceSizeBytes: 289187,
    outputSizeBytes: 289187,
    sectionId: "environment-zone-nursery",
    roomId: "environment-room-nursery-newborn",
  },
  {
    imageId: "static:environment/nursery/newborn/2",
    url: "/real-photos/environment/nursery/newborn/2.jpg",
    sourceRelativePath: "supplement/environment/nursery-3-01.jpg",
    target: "environment",
    targetId: "environment-zone-nursery",
    slot: "room",
    order: 2,
    originalFileName: "nursery-3-01.jpg",
    outputFileName: "2.jpg",
    sourceWidth: 1279,
    sourceHeight: 1706,
    outputWidth: 1279,
    outputHeight: 1706,
    sourceSizeBytes: 295169,
    outputSizeBytes: 295169,
    sectionId: "environment-zone-nursery",
    roomId: "environment-room-nursery-newborn",
  },
  {
    imageId: "static:environment/nursery/newborn/3",
    url: "/real-photos/environment/nursery/newborn/3.jpg",
    sourceRelativePath: "supplement/environment/nursery-3-02.jpg",
    target: "environment",
    targetId: "environment-zone-nursery",
    slot: "room",
    order: 3,
    originalFileName: "nursery-3-02.jpg",
    outputFileName: "3.jpg",
    sourceWidth: 1706,
    sourceHeight: 1279,
    outputWidth: 1706,
    outputHeight: 1279,
    sourceSizeBytes: 284043,
    outputSizeBytes: 284043,
    sectionId: "environment-zone-nursery",
    roomId: "environment-room-nursery-newborn",
  },
  {
    imageId: "static:environment/king/room-1/1",
    url: "/real-photos/environment/king/room-1/1.jpg",
    sourceRelativePath: "supplement/environment/king-room-1-00.jpg",
    target: "environment",
    targetId: "environment-zone-king",
    slot: "room",
    order: 1,
    originalFileName: "king-room-1-00.jpg",
    outputFileName: "1.jpg",
    sourceWidth: 1279,
    sourceHeight: 1706,
    outputWidth: 1279,
    outputHeight: 1706,
    sourceSizeBytes: 119655,
    outputSizeBytes: 119655,
    sectionId: "environment-zone-king",
    roomId: "environment-room-king-1",
  },
  {
    imageId: "static:environment/king/room-1/2",
    url: "/real-photos/environment/king/room-1/2.jpg",
    sourceRelativePath: "supplement/environment/king-room-1-01.jpg",
    target: "environment",
    targetId: "environment-zone-king",
    slot: "room",
    order: 2,
    originalFileName: "king-room-1-01.jpg",
    outputFileName: "2.jpg",
    sourceWidth: 1706,
    sourceHeight: 1279,
    outputWidth: 1706,
    outputHeight: 1279,
    sourceSizeBytes: 123636,
    outputSizeBytes: 123636,
    sectionId: "environment-zone-king",
    roomId: "environment-room-king-1",
  },
  {
    imageId: "static:environment/king/room-2/1",
    url: "/real-photos/environment/king/room-2/1.jpg",
    sourceRelativePath: "supplement/environment/king-room-2-00.jpg",
    target: "environment",
    targetId: "environment-zone-king",
    slot: "room",
    order: 1,
    originalFileName: "king-room-2-00.jpg",
    outputFileName: "1.jpg",
    sourceWidth: 1706,
    sourceHeight: 1279,
    outputWidth: 1706,
    outputHeight: 1279,
    sourceSizeBytes: 152524,
    outputSizeBytes: 152524,
    sectionId: "environment-zone-king",
    roomId: "environment-room-king-2",
  },
  {
    imageId: "static:environment/king/room-2/2",
    url: "/real-photos/environment/king/room-2/2.jpg",
    sourceRelativePath: "supplement/environment/king-room-2-01.jpg",
    target: "environment",
    targetId: "environment-zone-king",
    slot: "room",
    order: 2,
    originalFileName: "king-room-2-01.jpg",
    outputFileName: "2.jpg",
    sourceWidth: 1279,
    sourceHeight: 1706,
    outputWidth: 1279,
    outputHeight: 1706,
    sourceSizeBytes: 138036,
    outputSizeBytes: 138036,
    sectionId: "environment-zone-king",
    roomId: "environment-room-king-2",
  },
  {
    imageId: "static:environment/king/room-3/1",
    url: "/real-photos/environment/king/room-3/1.jpg",
    sourceRelativePath: "supplement/environment/king-room-3-00.jpg",
    target: "environment",
    targetId: "environment-zone-king",
    slot: "room",
    order: 1,
    originalFileName: "king-room-3-00.jpg",
    outputFileName: "1.jpg",
    sourceWidth: 1706,
    sourceHeight: 1279,
    outputWidth: 1706,
    outputHeight: 1279,
    sourceSizeBytes: 131828,
    outputSizeBytes: 131828,
    sectionId: "environment-zone-king",
    roomId: "environment-room-king-3",
  },
  {
    imageId: "static:environment/king/room-3/2",
    url: "/real-photos/environment/king/room-3/2.jpg",
    sourceRelativePath: "supplement/environment/king-room-3-01.jpg",
    target: "environment",
    targetId: "environment-zone-king",
    slot: "room",
    order: 2,
    originalFileName: "king-room-3-01.jpg",
    outputFileName: "2.jpg",
    sourceWidth: 1279,
    sourceHeight: 1706,
    outputWidth: 1279,
    outputHeight: 1706,
    sourceSizeBytes: 159708,
    outputSizeBytes: 159708,
    sectionId: "environment-zone-king",
    roomId: "environment-room-king-3",
  },
  {
    imageId: "static:environment/king/outdoor/1",
    url: "/real-photos/environment/king/outdoor/1.jpg",
    sourceRelativePath: "supplement/environment/king-outdoor-00.jpg",
    target: "environment",
    targetId: "environment-zone-king",
    slot: "room",
    order: 1,
    originalFileName: "king-outdoor-00.jpg",
    outputFileName: "1.jpg",
    sourceWidth: 4080,
    sourceHeight: 3060,
    outputWidth: 4080,
    outputHeight: 3060,
    sourceSizeBytes: 2545397,
    outputSizeBytes: 2545397,
    sectionId: "environment-zone-king",
    roomId: "environment-room-king-outdoor",
  },
  {
    imageId: "static:environment/king/outdoor/2",
    url: "/real-photos/environment/king/outdoor/2.jpg",
    sourceRelativePath: "supplement/environment/king-outdoor-01.jpg",
    target: "environment",
    targetId: "environment-zone-king",
    slot: "room",
    order: 2,
    originalFileName: "king-outdoor-01.jpg",
    outputFileName: "2.jpg",
    sourceWidth: 4080,
    sourceHeight: 3060,
    outputWidth: 4080,
    outputHeight: 3060,
    sourceSizeBytes: 2548016,
    outputSizeBytes: 2548016,
    sectionId: "environment-zone-king",
    roomId: "environment-room-king-outdoor",
  },
  {
    imageId: "static:environment/king/outdoor/3",
    url: "/real-photos/environment/king/outdoor/3.jpg",
    sourceRelativePath: "supplement/environment/king-outdoor-02.jpg",
    target: "environment",
    targetId: "environment-zone-king",
    slot: "room",
    order: 3,
    originalFileName: "king-outdoor-02.jpg",
    outputFileName: "3.jpg",
    sourceWidth: 4096,
    sourceHeight: 3072,
    outputWidth: 4096,
    outputHeight: 3072,
    sourceSizeBytes: 2697683,
    outputSizeBytes: 2697683,
    sectionId: "environment-zone-king",
    roomId: "environment-room-king-outdoor",
  },
  {
    imageId: "static:environment/queen/common/1",
    url: "/real-photos/environment/queen/common/1.jpg",
    sourceRelativePath: "supplement/environment/queen-common-00.jpg",
    target: "environment",
    targetId: "environment-zone-queen",
    slot: "room",
    order: 1,
    originalFileName: "queen-common-00.jpg",
    outputFileName: "1.jpg",
    sourceWidth: 1279,
    sourceHeight: 1706,
    outputWidth: 1279,
    outputHeight: 1706,
    sourceSizeBytes: 183540,
    outputSizeBytes: 183540,
    sectionId: "environment-zone-queen",
    roomId: "environment-room-queen-common",
  },
  {
    imageId: "static:environment/queen/common/2",
    url: "/real-photos/environment/queen/common/2.jpg",
    sourceRelativePath: "supplement/environment/queen-common-01.jpg",
    target: "environment",
    targetId: "environment-zone-queen",
    slot: "room",
    order: 2,
    originalFileName: "queen-common-01.jpg",
    outputFileName: "2.jpg",
    sourceWidth: 1279,
    sourceHeight: 1706,
    outputWidth: 1279,
    outputHeight: 1706,
    sourceSizeBytes: 203520,
    outputSizeBytes: 203520,
    sectionId: "environment-zone-queen",
    roomId: "environment-room-queen-common",
  },
  {
    imageId: "static:feeding/combined/1",
    url: "/real-photos/feeding/combined/1.jpg",
    sourceRelativePath: "喂养照片√/00.jpg",
    target: "feeding",
    targetId: "feeding-module-kibble",
    slot: "gallery",
    order: 1,
    originalFileName: "00.jpg",
    outputFileName: "1.jpg",
    sourceWidth: 4096,
    sourceHeight: 3072,
    outputWidth: 2000,
    outputHeight: 1500,
    sourceSizeBytes: 4333902,
    outputSizeBytes: 402783,
  },
  {
    imageId: "static:feeding/supplements/1",
    url: "/real-photos/feeding/supplements/1.jpg",
    sourceRelativePath: "喂养照片√/01.jpg",
    target: "feeding",
    targetId: "feeding-module-supplements",
    slot: "gallery",
    order: 1,
    originalFileName: "01.jpg",
    outputFileName: "1.jpg",
    sourceWidth: 4096,
    sourceHeight: 3072,
    outputWidth: 2000,
    outputHeight: 1500,
    sourceSizeBytes: 4143529,
    outputSizeBytes: 376146,
  },
  {
    imageId: "static:feeding/cooked/1",
    url: "/real-photos/feeding/cooked/1.jpg",
    sourceRelativePath: "喂养照片√/02.jpg",
    target: "feeding",
    targetId: "feeding-module-cooked",
    slot: "gallery",
    order: 1,
    originalFileName: "02.jpg",
    outputFileName: "1.jpg",
    sourceWidth: 1279,
    sourceHeight: 1706,
    outputWidth: 1280,
    outputHeight: 1706,
    sourceSizeBytes: 228019,
    outputSizeBytes: 143311,
  },
  {
    imageId: "static:feeding/cooked/2",
    url: "/real-photos/feeding/cooked/2.jpg",
    sourceRelativePath: "喂养照片√/03.jpg",
    target: "feeding",
    targetId: "feeding-module-cooked",
    slot: "gallery",
    order: 2,
    originalFileName: "03.jpg",
    outputFileName: "2.jpg",
    sourceWidth: 1279,
    sourceHeight: 1706,
    outputWidth: 1280,
    outputHeight: 1706,
    sourceSizeBytes: 338343,
    outputSizeBytes: 275394,
  },
  {
    imageId: "static:feeding/cooked/3",
    url: "/real-photos/feeding/cooked/3.jpg",
    sourceRelativePath: "喂养照片√/04.jpg",
    target: "feeding",
    targetId: "feeding-module-cooked",
    slot: "gallery",
    order: 3,
    originalFileName: "04.jpg",
    outputFileName: "3.jpg",
    sourceWidth: 1279,
    sourceHeight: 1706,
    outputWidth: 1280,
    outputHeight: 1706,
    sourceSizeBytes: 314054,
    outputSizeBytes: 258107,
  },
  {
    imageId: "static:feeding/cooked/4",
    url: "/real-photos/feeding/cooked/4.jpg",
    sourceRelativePath: "喂养照片√/05.jpg",
    target: "feeding",
    targetId: "feeding-module-cooked",
    slot: "gallery",
    order: 4,
    originalFileName: "05.jpg",
    outputFileName: "4.jpg",
    sourceWidth: 1279,
    sourceHeight: 1706,
    outputWidth: 1280,
    outputHeight: 1706,
    sourceSizeBytes: 258517,
    outputSizeBytes: 183806,
  },
] as const satisfies readonly RealPhotoAsset[];

export const REAL_PHOTO_ASSET_MAP = Object.fromEntries(
  REAL_PHOTO_ASSETS.map((asset) => [asset.imageId, asset]),
) as Record<string, (typeof REAL_PHOTO_ASSETS)[number]>;

export const STUD_REAL_IMAGE_ASSIGNMENTS = {
  chonglou: {
    coverImageId: "static:studs/chonglou/cover",
    galleryImageIds: ["static:studs/chonglou/gallery-1", "static:studs/chonglou/gallery-2"],
  },
  shulongyin: {
    coverImageId: "static:studs/shulongyin/cover",
    galleryImageIds: ["static:studs/shulongyin/gallery-1", "static:studs/shulongyin/gallery-2"],
  },
  tianhe: {
    coverImageId: "static:studs/tianhe/cover",
    galleryImageIds: ["static:studs/tianhe/gallery-1", "static:studs/tianhe/gallery-2"],
  },
  huqing: {
    coverImageId: "static:studs/huqing/cover",
    galleryImageIds: ["static:studs/huqing/gallery-1", "static:studs/huqing/gallery-2"],
  },
  yunmu: {
    coverImageId: "static:studs/yunmu/cover",
    galleryImageIds: [
      "static:studs/yunmu/gallery-1",
      "static:studs/yunmu/gallery-2",
      "static:studs/yunmu/gallery-3",
    ],
  },
  guihuagao: {
    coverImageId: "static:studs/guihuagao/cover",
    galleryImageIds: ["static:studs/guihuagao/gallery-1", "static:studs/guihuagao/gallery-2"],
  },
  luoyiyi: {
    coverImageId: "static:studs/luoyiyi/cover",
    galleryImageIds: ["static:studs/luoyiyi/gallery-1", "static:studs/luoyiyi/gallery-2"],
  },
  hupo: {
    coverImageId: "static:studs/hupo/cover",
    galleryImageIds: ["static:studs/hupo/gallery-1", "static:studs/hupo/gallery-2"],
  },
  niaotuan: {
    coverImageId: "static:studs/niaotuan/cover",
    galleryImageIds: ["static:studs/niaotuan/gallery-1", "static:studs/niaotuan/gallery-2"],
  },
  xiongmao: {
    coverImageId: "static:studs/xiongmao/cover",
    galleryImageIds: ["static:studs/xiongmao/gallery-1", "static:studs/xiongmao/gallery-2"],
  },
  zhaoyue: {
    coverImageId: "static:studs/zhaoyue/cover",
    galleryImageIds: ["static:studs/zhaoyue/gallery-1", "static:studs/zhaoyue/gallery-2"],
  },
  xiaobianmu: {
    coverImageId: "static:studs/xiaobianmu/cover",
    galleryImageIds: ["static:studs/xiaobianmu/gallery-1", "static:studs/xiaobianmu/gallery-2"],
  },
  xiaoxiaxian: {
    coverImageId: "static:studs/xiaoxiaxian/cover",
    galleryImageIds: ["static:studs/xiaoxiaxian/gallery-1", "static:studs/xiaoxiaxian/gallery-2"],
  },
  manao: {
    coverImageId: "static:studs/manao/cover",
    galleryImageIds: ["static:studs/manao/gallery-1", "static:studs/manao/gallery-2"],
  },
  xiaotao: {
    coverImageId: "static:studs/xiaotao/cover",
    galleryImageIds: ["static:studs/xiaotao/gallery-1", "static:studs/xiaotao/gallery-2"],
  },
} as const;

export const ENVIRONMENT_REAL_IMAGE_ASSIGNMENTS = {
  "environment-zone-nursery": {
    coverImageId: "static:environment/nursery/pregnancy/1",
    rooms: {
      "environment-room-nursery-pregnancy": [
        "static:environment/nursery/pregnancy/1",
        "static:environment/nursery/pregnancy/2",
      ],
      "environment-room-nursery-newborn": [
        "static:environment/nursery/newborn/1",
        "static:environment/nursery/newborn/2",
        "static:environment/nursery/newborn/3",
      ],
    },
  },
  "environment-zone-kitten": {
    coverImageId: "static:environment/kitten/room-1/1",
    rooms: {
      "environment-room-kitten-1": [
        "static:environment/kitten/room-1/1",
        "static:environment/kitten/room-1/2",
        "static:environment/kitten/room-1/3",
        "static:environment/kitten/room-1/4",
      ],
      "environment-room-kitten-2": [
        "static:environment/kitten/room-2/1",
        "static:environment/kitten/room-2/2",
        "static:environment/kitten/room-2/3",
      ],
      "environment-room-kitten-3": [
        "static:environment/kitten/room-3/1",
        "static:environment/kitten/room-3/2",
        "static:environment/kitten/room-3/3",
      ],
      "environment-room-kitten-common": [
        "static:environment/kitten/room-common/1",
        "static:environment/kitten/room-common/2",
        "static:environment/kitten/room-common/3",
        "static:environment/kitten/room-common/4",
        "static:environment/kitten/room-common/5",
      ],
    },
  },
  "environment-zone-queen": {
    coverImageId: "static:environment/queen/room-1/1",
    rooms: {
      "environment-room-queen-1": [
        "static:environment/queen/room-1/1",
        "static:environment/queen/room-1/2",
        "static:environment/queen/room-1/3",
        "static:environment/queen/room-1/4",
        "static:environment/queen/room-1/5",
      ],
      "environment-room-queen-2": [
        "static:environment/queen/room-2/1",
        "static:environment/queen/room-2/2",
        "static:environment/queen/room-2/3",
      ],
      "environment-room-queen-3": [
        "static:environment/queen/room-3/1",
        "static:environment/queen/room-3/2",
        "static:environment/queen/room-3/3",
      ],
      "environment-room-queen-4": [
        "static:environment/queen/room-4/1",
        "static:environment/queen/room-4/2",
        "static:environment/queen/room-4/3",
      ],
      "environment-room-queen-common": [
        "static:environment/queen/common/1",
        "static:environment/queen/common/2",
      ],
    },
  },
  "environment-zone-king": {
    coverImageId: "static:environment/king/room-1/1",
    rooms: {
      "environment-room-king-1": [
        "static:environment/king/room-1/1",
        "static:environment/king/room-1/2",
      ],
      "environment-room-king-2": [
        "static:environment/king/room-2/1",
        "static:environment/king/room-2/2",
      ],
      "environment-room-king-3": [
        "static:environment/king/room-3/1",
        "static:environment/king/room-3/2",
      ],
      "environment-room-king-outdoor": [
        "static:environment/king/outdoor/1",
        "static:environment/king/outdoor/2",
        "static:environment/king/outdoor/3",
      ],
    },
  },
} as const;

export const REAL_PHOTO_IMPORT_AUDIT = {
  sourceAudit: {
    root: "D:\\xwechat_files\\wxid_o08o8otqh98r22_5ff2\\msg\\file\\2026-08\\小程序文件整合",
    top_level_folders: [
      "喂养照片√",
      "我们的猫丨小猫",
      "我们的猫丨种猫",
      "猫舍介绍",
      "猫舍环境",
      "窝次照片",
      "首图轮播",
    ],
    second_level_folders: {
      "喂养照片√": [],
      我们的猫丨小猫: [],
      我们的猫丨种猫: ["公猫", "母猫"],
      猫舍介绍: [],
      猫舍环境: ["公共活动区", "公猫生活区", "幼猫生活区√", "母婴生活区", "母猫生活区√"],
      窝次照片: [],
      首图轮播: [],
    },
    total_files_seen: 89,
    image_candidate_count: 89,
    supported_count: 89,
    unsupported_count: 0,
    damaged_count: 0,
    duplicate_group_count: 1,
    duplicate_file_count: 2,
    format_counts: {
      jpg: 89,
    },
    orientation_counts: {
      landscape: 17,
      portrait: 72,
    },
    total_size_bytes: 511691798,
    supported_total_size_bytes: 511691798,
    unsupported_files: [],
    damaged_files: [],
  },
  processedSummary: {
    selectedSourceImageCount: 71,
    selectedSourceTotalSizeBytes: 417521328,
    outputImageCount: 71,
    outputTotalSizeBytes: 23968131,
    maxEdge: 2000,
    jpegQuality: 88,
  },
  unresolved: {
    empty_source_directories: ["首图轮播", "猫舍介绍", "我们的猫丨小猫", "窝次照片"],
    stud_requires_confirmation: [
      "我们的猫丨种猫/母猫/种猫-卡比-00.jpg",
      "我们的猫丨种猫/母猫/种猫-卡比-01.jpg",
      "我们的猫丨种猫/母猫/种猫-卡比-02.jpg",
      "我们的猫丨种猫/母猫/种猫-洛水-00.jpg",
      "我们的猫丨种猫/母猫/种猫-洛水-01.jpg",
      "我们的猫丨种猫/母猫/种猫-洛水-02.jpg",
      "我们的猫丨种猫/母猫/种猫-红豆-00.jpg",
      "我们的猫丨种猫/母猫/种猫-红豆-01.jpg",
      "我们的猫丨种猫/母猫/种猫-红豆-02.jpg",
      "我们的猫丨种猫/母猫/种猫-钟灵-00.jpg",
      "我们的猫丨种猫/母猫/种猫-钟灵-01.jpg",
      "我们的猫丨种猫/母猫/种猫-钟灵-02.jpg",
    ],
    environment_requires_confirmation: [
      "猫舍环境/母猫生活区√/母猫房5-00.jpg",
      "猫舍环境/母猫生活区√/母猫房5-01.jpg",
      "猫舍环境/母猫生活区√/母猫房5-02.jpg",
      "猫舍环境/母猫生活区√/母猫房5-03.jpg",
      "猫舍环境/母猫生活区√/母猫房3-03.jpg",
      "猫舍环境/母猫生活区√/母猫房4-02.jpg",
    ],
    duplicate_source_groups: [
      ["猫舍环境/母猫生活区√/母猫房3-03.jpg", "猫舍环境/母猫生活区√/母猫房4-02.jpg"],
    ],
    temporary_cover_selections: [
      {
        target: "stud:zhaoyue",
        sourceRelativePath: "我们的猫丨种猫/母猫/种猫-昭月-01.jpg",
        reason: "缺少 00 / cover / 封面文件名，按自然排序第一张临时作为封面。",
      },
    ],
  },
} as const;

export function getStaticImageUrl(imageId: string | null | undefined) {
  if (!imageId || !imageId.startsWith(STATIC_REAL_IMAGE_PREFIX)) return undefined;
  return REAL_PHOTO_ASSET_MAP[imageId]?.url;
}
