/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudsRouteImport } from './routes/studs'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuestionnaireRouteImport } from './routes/questionnaire'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as MoreRouteImport } from './routes/more'
import { Route as FeedingRouteImport } from './routes/feeding'
import { Route as EnvironmentRouteImport } from './routes/environment'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KittensIndexRouteImport } from './routes/kittens.index'
import { Route as KittensIdRouteImport } from './routes/kittens.$id'

const StudsRoute = StudsRouteImport.update({
  id: '/studs',
  path: '/studs',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireRoute = QuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedingRoute = FeedingRouteImport.update({
  id: '/feeding',
  path: '/feeding',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentRoute = EnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KittensIndexRoute = KittensIndexRouteImport.update({
  id: '/kittens/',
  path: '/kittens/',
  getParentRoute: () => rootRouteImport,
} as any)
const KittensIdRoute = KittensIdRouteImport.update({
  id: '/kittens/$id',
  path: '/kittens/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/environment': typeof EnvironmentRoute
  '/feeding': typeof FeedingRoute
  '/more': typeof MoreRoute
  '/philosophy': typeof PhilosophyRoute
  '/process': typeof ProcessRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studs': typeof StudsRoute
  '/kittens/$id': typeof KittensIdRoute
  '/kittens/': typeof KittensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/environment': typeof EnvironmentRoute
  '/feeding': typeof FeedingRoute
  '/more': typeof MoreRoute
  '/philosophy': typeof PhilosophyRoute
  '/process': typeof ProcessRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studs': typeof StudsRoute
  '/kittens/$id': typeof KittensIdRoute
  '/kittens': typeof KittensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/environment': typeof EnvironmentRoute
  '/feeding': typeof FeedingRoute
  '/more': typeof MoreRoute
  '/philosophy': typeof PhilosophyRoute
  '/process': typeof ProcessRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studs': typeof StudsRoute
  '/kittens/$id': typeof KittensIdRoute
  '/kittens/': typeof KittensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/environment'
    | '/feeding'
    | '/more'
    | '/philosophy'
    | '/process'
    | '/questionnaire'
    | '/sitemap.xml'
    | '/studs'
    | '/kittens/$id'
    | '/kittens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/environment'
    | '/feeding'
    | '/more'
    | '/philosophy'
    | '/process'
    | '/questionnaire'
    | '/sitemap.xml'
    | '/studs'
    | '/kittens/$id'
    | '/kittens'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/environment'
    | '/feeding'
    | '/more'
    | '/philosophy'
    | '/process'
    | '/questionnaire'
    | '/sitemap.xml'
    | '/studs'
    | '/kittens/$id'
    | '/kittens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  EnvironmentRoute: typeof EnvironmentRoute
  FeedingRoute: typeof FeedingRoute
  MoreRoute: typeof MoreRoute
  PhilosophyRoute: typeof PhilosophyRoute
  ProcessRoute: typeof ProcessRoute
  QuestionnaireRoute: typeof QuestionnaireRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudsRoute: typeof StudsRoute
  KittensIdRoute: typeof KittensIdRoute
  KittensIndexRoute: typeof KittensIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studs': {
      id: '/studs'
      path: '/studs'
      fullPath: '/studs'
      preLoaderRoute: typeof StudsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire': {
      id: '/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeding': {
      id: '/feeding'
      path: '/feeding'
      fullPath: '/feeding'
      preLoaderRoute: typeof FeedingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environment': {
      id: '/environment'
      path: '/environment'
      fullPath: '/environment'
      preLoaderRoute: typeof EnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kittens/': {
      id: '/kittens/'
      path: '/kittens'
      fullPath: '/kittens/'
      preLoaderRoute: typeof KittensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kittens/$id': {
      id: '/kittens/$id'
      path: '/kittens/$id'
      fullPath: '/kittens/$id'
      preLoaderRoute: typeof KittensIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  EnvironmentRoute: EnvironmentRoute,
  FeedingRoute: FeedingRoute,
  MoreRoute: MoreRoute,
  PhilosophyRoute: PhilosophyRoute,
  ProcessRoute: ProcessRoute,
  QuestionnaireRoute: QuestionnaireRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudsRoute: StudsRoute,
  KittensIdRoute: KittensIdRoute,
  KittensIndexRoute: KittensIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
