/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuestionnaireRouteImport } from './routes/questionnaire'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as FeedingRouteImport } from './routes/feeding'
import { Route as EnvironmentRouteImport } from './routes/environment'
import { Route as CatsRouteImport } from './routes/cats'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudsIdRouteImport } from './routes/studs.$id'
import { Route as KittensIdRouteImport } from './routes/kittens.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireRoute = QuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedingRoute = FeedingRouteImport.update({
  id: '/feeding',
  path: '/feeding',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentRoute = EnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => rootRouteImport,
} as any)
const CatsRoute = CatsRouteImport.update({
  id: '/cats',
  path: '/cats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudsIdRoute = StudsIdRouteImport.update({
  id: '/studs/$id',
  path: '/studs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KittensIdRoute = KittensIdRouteImport.update({
  id: '/kittens/$id',
  path: '/kittens/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cats': typeof CatsRoute
  '/environment': typeof EnvironmentRoute
  '/feeding': typeof FeedingRoute
  '/philosophy': typeof PhilosophyRoute
  '/process': typeof ProcessRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kittens/$id': typeof KittensIdRoute
  '/studs/$id': typeof StudsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cats': typeof CatsRoute
  '/environment': typeof EnvironmentRoute
  '/feeding': typeof FeedingRoute
  '/philosophy': typeof PhilosophyRoute
  '/process': typeof ProcessRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kittens/$id': typeof KittensIdRoute
  '/studs/$id': typeof StudsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cats': typeof CatsRoute
  '/environment': typeof EnvironmentRoute
  '/feeding': typeof FeedingRoute
  '/philosophy': typeof PhilosophyRoute
  '/process': typeof ProcessRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kittens/$id': typeof KittensIdRoute
  '/studs/$id': typeof StudsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cats'
    | '/environment'
    | '/feeding'
    | '/philosophy'
    | '/process'
    | '/questionnaire'
    | '/sitemap.xml'
    | '/kittens/$id'
    | '/studs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/cats'
    | '/environment'
    | '/feeding'
    | '/philosophy'
    | '/process'
    | '/questionnaire'
    | '/sitemap.xml'
    | '/kittens/$id'
    | '/studs/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cats'
    | '/environment'
    | '/feeding'
    | '/philosophy'
    | '/process'
    | '/questionnaire'
    | '/sitemap.xml'
    | '/kittens/$id'
    | '/studs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CatsRoute: typeof CatsRoute
  EnvironmentRoute: typeof EnvironmentRoute
  FeedingRoute: typeof FeedingRoute
  PhilosophyRoute: typeof PhilosophyRoute
  ProcessRoute: typeof ProcessRoute
  QuestionnaireRoute: typeof QuestionnaireRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  KittensIdRoute: typeof KittensIdRoute
  StudsIdRoute: typeof StudsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire': {
      id: '/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeding': {
      id: '/feeding'
      path: '/feeding'
      fullPath: '/feeding'
      preLoaderRoute: typeof FeedingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environment': {
      id: '/environment'
      path: '/environment'
      fullPath: '/environment'
      preLoaderRoute: typeof EnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cats': {
      id: '/cats'
      path: '/cats'
      fullPath: '/cats'
      preLoaderRoute: typeof CatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studs/$id': {
      id: '/studs/$id'
      path: '/studs/$id'
      fullPath: '/studs/$id'
      preLoaderRoute: typeof StudsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kittens/$id': {
      id: '/kittens/$id'
      path: '/kittens/$id'
      fullPath: '/kittens/$id'
      preLoaderRoute: typeof KittensIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CatsRoute: CatsRoute,
  EnvironmentRoute: EnvironmentRoute,
  FeedingRoute: FeedingRoute,
  PhilosophyRoute: PhilosophyRoute,
  ProcessRoute: ProcessRoute,
  QuestionnaireRoute: QuestionnaireRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  KittensIdRoute: KittensIdRoute,
  StudsIdRoute: StudsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
